import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

/**
 * Prisma config for the better-auth database (separate from the app database).
 * The models are generated by `@better-auth/cli generate` — see
 * `prisma/auth/schema.prisma` and the `*:auth` package scripts.
 */
export default defineConfig({
  schema: 'prisma/auth/schema.prisma',
  migrations: {
    path: 'prisma/auth/migrations',
  },
  datasource: {
    url: env('AUTH_DATABASE_URL'),
  },
});
